server:
  port: 8092
  servlet:
    context-path: /property-view
spring:
  application:
    name: hotel
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    persistAuthorization: true
  api-docs:
    path: /v3/api-docs